/*
 XSDexplicitGroup.h
 The implementation of properties and methods for the XSDexplicitGroup object.
 Generated by SudzC.com
 */
#import "XSDexplicitGroup.h"
#import "XSDSchema.h"
#import "XSDelement.h"
#import "XMLUtils.h"

@interface XSDexplicitGroup ()

@property (strong, nonatomic) NSString* name;
@property (strong, nonatomic) NSString* ref;
@property (strong, nonatomic) NSArray* elements;

@end

@implementation XSDexplicitGroup

- (id) initWithNode: (NSXMLElement*) node schema: (XSDschema*) schema {
    self = [super initWithNode:node schema: schema];
    if(self) {
        self.name = [XMLUtils node: node stringAttribute: @"name"];
        self.ref = [XMLUtils node: node stringAttribute: @"ref"];
        
        if(!self.name)
            self.name = @"XS";
        
        NSMutableArray* newElements = [NSMutableArray array];
        NSArray* elementTags = [XMLUtils node:node descendantsWithName: @"element"];
        for(NSXMLElement* anElement in elementTags) {
            [newElements addObject: [[XSDelement alloc] initWithNode: anElement schema: schema]];
        }
        self.elements = newElements;
    }
    return self;
}

@end
