/*
 XSDelement.h
 The interface definition of properties and methods for the XSDelement object.
 Generated by SudzC.com
 */


#import "XSSchemaNode.h"

@class XSDcomplexType;
@protocol XSType;

@interface XSDelement : XSSchemaNode

@property (readonly, nonatomic) id<XSType> localType;
@property (readonly, nonatomic) NSString* name;
@property (readonly, nonatomic) NSString* type;
@property (readonly, nonatomic) NSString* substitutionGroup;
@property (readonly, nonatomic) NSString* defaultValue;
@property (readonly, nonatomic) NSString* fixed;
@property (readonly, nonatomic) NSString* nillable;
@property (readonly, nonatomic) NSString* abstractValue;
@property (readonly, nonatomic) NSString* final;
@property (readonly, nonatomic) NSString* block;
@property (readonly, nonatomic) NSString* form;
@property (readonly, nonatomic) NSNumber* minOccurs;
@property (readonly, nonatomic) NSNumber* maxOccurs;

- (NSString*) readCodeForContent;
- (NSString*) variableName; //in generated code

- (BOOL) isSingleValue;

- (id<XSType>) schemaType;
- (BOOL) hasEnumeration;
- (NSString*) codeType;

@end
